import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import { ReactNode } from "react"
import Navbar from "../Components/Navbar"
import Footer from "../Components/Footer"
import { AuthProvider } from "../context/AuthProvider" // Ensure named export

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "My Next.js App",
  description: "Generated by SHAWON0c",
}

type RootLayoutProps = {
  children: ReactNode
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black text-yellow-400`}
      >
        <AuthProvider>
          <Navbar />
          <main>{children}</main>
          {/* <Footer /> */}
        </AuthProvider>
      </body>
    </html>
  )
}
